### ISSUE TITLE
Add a whitespace after "=" 

### ISSUE THREAD

**Issue by saket** [suusan2go/kotlin-fill-class#125]
Thanks for maintaining this plugin @suusan2go! Would you be able to add a whitespace character after each `=` when filling parameters? This will save me an auto-format after performing a fill. 

https://github.com/suusan2go/kotlin-fill-class/assets/2387680/4933a063-eba5-4012-b62f-ab2ee17c30d5

**Comment by oboenikui** [comment]
@saket 
Due to IDEA specifications, this does not appear to be possible.
If the plugin rewrites code through the Inspection, IDEA automatically reformats the code. This means that if the plugin outputs code with spaces, they will be erased automatically.
As a workaround, disable the `Fill arguments without default values` option and have the plugin output dummy default values, so the code is error-free and the formatter will automatically insert spaces.
