### ISSUE TITLE
I'm using version 2022.3.3 and it doesn't work anymore

### ISSUE THREAD

**Issue by lyang0932** [suusan2go/kotlin-fill-class#99]
I'm using version 2022.3.3 and it doesn't work anymore

<img width="598" alt="image" src="https://user-images.githubusercontent.com/33677473/236223016-da72a9b3-92fb-4873-b589-745dd96f59ba.png">
<img width="429" alt="image" src="https://user-images.githubusercontent.com/33677473/236223197-1541d796-c471-40d6-99d9-3a9e63f385a2.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/33677473/236223512-8a843b24-c700-4658-a498-96bc9e61ddad.png">

**Comment by oboenikui** [comment]
@lyang0932 Thanks for reporting.

First, please let me know if it is applicable the following two cases.

1. Is the constructor or function implemented in Java, not Kotlin?
2. Does the constructor or function have any overloads?

If applicable, this plugin will not work.
(In case 1, because Kotlin's named argument feature does not work; in case 2, because the information of the parameter to be filled is not uniquely determined.)

Could you please check if it works with the following classes and functions?

**Comment by oboenikui** [comment]
Duplicate of #86

**Comment by lyang0932** [comment]
I am here again , now I use 2023.1.1 version.
And it still now work , I will show my code , please help me , thanks.
<img width="468" alt="image" src="https://github.com/suusan2go/kotlin-fill-class/assets/33677473/6adb2596-b983-4c64-830f-e3f37d4d3d8f">
<img width="445" alt="image" src="https://github.com/suusan2go/kotlin-fill-class/assets/33677473/c696fdb7-06fe-417a-94e5-e1d69fe89b07">

**Comment by lyang0932** [comment]
You are right ! It works again!
